### ISSUE TITLE
Are discrete genomic features supported?

### ISSUE THREAD

**Issue by jydu** [yifei-lab/MK-regression#1]
Hi Yi-Fei,

I was wondering whether the MKregression would work with discrete genomic features, like gene categories for instance. Can one code a feature as "A", "B", "C", "D", etc., or maybe should separated binary columns be made, like feature A 0/1, feature B 0/1, etc. ?

Thanks a lot in advance for your insights,

Julien.

**Comment by yifei-lab** [comment]
Hi Julien,

Thanks for asking. That's a great question! In the current implementation of MK regression, we need to convert categorical variables to dummy variables. For instance, if we have a feature with four levels ("A", "B", "C", "D") and assume "D" is the baseline level, we need to create three binary dummy variables for "A", "B", and "C." It is worth noting that we cannot create a dummy variable for the baseline level "D." Otherwise, the model will be overparameterized and unidentifiable.

Best,
Yifei

**Comment by jydu** [comment]
Dear Yifei,

Thanks a lot for your prompt answer, I will give it a go!

All the best,

Julien.
